export const Experience = [
  {
    image: './assets/seekir_logo.jpg',
    width: '80',
    alt: 'Logo',
    Title: 'Seekir',
    Role: 'Co-Founder', 
    Date: '/ April 2025 - Present',
    Description: 'Co-founded Seekir, a startup connecting students to research opportunities. Developed the website using Next.js and TailwindCSS, focusing on user experience and functionality. Implemented features to streamline the application process for students and researchers.',
  },
  {
    image: './assets/emory.png',
    width: '80',
    alt: 'Logo',
    Title: 'Emory',
    Role: 'Research Assistant', 
    Date: '/ May 2025 - Present',
    Description: 'Conducting research at Emory University, Natural language processing, and bioinformatics',
  },
  {
    image: './assets/utaustin.webp',
    width: '80',
    alt: 'Logo',
    Title: 'UT-Austin',
    Role: 'Research Assistant', 
    Date: '/ August 2024 - Present',
    Description: 'Conducting research at UT, being mentored by Chandrajit Bajaj, Head of CV over artificial intelligence',
  },
  {
    image: './assets/statoracle_logo.jpg',
    width: '80',
    alt: 'Logo',
    Title: 'Stat-Oracle',
    Role: 'Frontend Dev | Founding Engineer', 
    Date: '/ June 2024 - Present',
    Description: 'Stat-Oracle is a soccer startup where users upload game clips to be processed with AI to gain stats and insights. Developed and optimized the user interface for a machine learning database, enhancing usability and user experience. Implemented a waitlist feature using the Waitlist API, improving customer acquisition and retention.',
  },
  {
    image: './assets/CortexPD.webp',
    width: '80',
    alt: 'Logo',
    Title: 'CortexPD',
    Role: 'Frontend Dev', 
    Date: '/ June 2024 - Present',
    Description: 'CortexPD is a nonprofit organization dedicated to improving the lives of people diagnosed with Parkinson\'s disorder. Designed and implemented a comprehensive website, focusing on user interface and overall design to improve user engagement.',
  },
]
