export const Projects = [
  {
    image: './assets/Neuro_S.png',
    width: '230',
    height: '',
    alt: 'Website_Image',
    title: 'CortexPD',
    date: 'June 2024',
    description: 'A website I created for CortexPD a nonprofit organization aimed at combating Parkinsons!',
    link: 'https://cortexpd.vercel.app/',
    repo: 'https://github.com/aadityapanchal7/NeuroCatalyst/',
    Languages: ['React', 'TailwindCSS', 'Javascript',],
  },
  {
    image: './assets/AP_Visuals_S.png',
    width: '200',
    height: '',
    alt: 'Website_Image',
    title: 'AP-Visuals',
    date: 'June 2024',
    description: 'A website I created to support my freelancing business. Multiple webpages, with flask backend.',
    link: 'https://ap-visuals.vercel.app/',
    repo: 'https://github.com/aadityapanchal7/ap-visuals',
    Languages: ['HTML', 'TailwindCSS', 'Javascript', 'Flask'],
  },
  {
    image: './assets/RMA.png',
    width: '240',
    height: '',
    alt: 'Website_Image',
    title: 'Research Made Accessible',
    date: 'May 2024',
    description: 'A static website created for a research nonprofit. My first project which incorporates NextJS.',
    link: 'https://www.researchmadeaccessible.org',
    repo: 'https://github.com/aadityapanchal7/rma',
    Languages: ['Next.js', 'TailwindCSS', 'React',],
  },
  {
    image: './assets/Portfolio_S.png',
    width: '300',
    height: '',
    alt: 'Website_Image',
    title: 'This Website',
    date: 'June 2024',
    description: 'This is the first iteration of my personal portfolio, built using React, and TailwindCSS :)',
    link: 'https://aadityapanchal.vercel.app',
    repo: 'https://github.com/aadityapanchal7/portfolio-v1',
    Languages: ['React', 'TailwindCSS'],
  },
]

